# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf5e41b9ac4c8ef393157e2cbc586f8dae4d468bc4ff9ad864b9ce52bec12111a7c48cf1729518e979d1adc443bb57abb00e748bec65afbb424c779c00b4c390

test:
  secret_key_base: 74f534a7d75a6f4e53b693036713f4373e4985cdd98092ed43b0d0c17e31f307df393dbe964413ed5f5549834ceae3bf92f82393db5810671533163647c6af4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
